//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillPaymentGroupAssignment.SagicorLifeServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Sagicor.com/webservices", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sagicor.com/webservices", ConfigurationName="SagicorLifeServices.SagicorLifeConnectSoap")]
    public interface SagicorLifeConnectSoap {
        
        // CODEGEN: Generating message contract since element name userAccNum from namespace http://Sagicor.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/CheckSagicor", ReplyAction="*")]
        BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse CheckSagicor(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/CheckSagicor", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse> CheckSagicorAsync(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest request);
        
        // CODEGEN: Generating message contract since element name accNum from namespace http://Sagicor.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/GetSagicorInfo", ReplyAction="*")]
        BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse GetSagicorInfo(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/GetSagicorInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse> GetSagicorInfoAsync(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest request);
        
        // CODEGEN: Generating message contract since element name accNum from namespace http://Sagicor.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/PaySagicor", ReplyAction="*")]
        BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse PaySagicor(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sagicor.com/webservices/PaySagicor", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse> PaySagicorAsync(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSagicorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSagicor", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequestBody Body;
        
        public CheckSagicorRequest() {
        }
        
        public CheckSagicorRequest(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class CheckSagicorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userAccNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userAccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userAccPhoneNum;
        
        public CheckSagicorRequestBody() {
        }
        
        public CheckSagicorRequestBody(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            this.userAccNum = userAccNum;
            this.userAccEmail = userAccEmail;
            this.userAccPhoneNum = userAccPhoneNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckSagicorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckSagicorResponse", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponseBody Body;
        
        public CheckSagicorResponse() {
        }
        
        public CheckSagicorResponse(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class CheckSagicorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckSagicorResult;
        
        public CheckSagicorResponseBody() {
        }
        
        public CheckSagicorResponseBody(bool CheckSagicorResult) {
            this.CheckSagicorResult = CheckSagicorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSagicorInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSagicorInfo", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequestBody Body;
        
        public GetSagicorInfoRequest() {
        }
        
        public GetSagicorInfoRequest(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class GetSagicorInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accNum;
        
        public GetSagicorInfoRequestBody() {
        }
        
        public GetSagicorInfoRequestBody(string accNum) {
            this.accNum = accNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSagicorInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSagicorInfoResponse", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponseBody Body;
        
        public GetSagicorInfoResponse() {
        }
        
        public GetSagicorInfoResponse(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class GetSagicorInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.ArrayOfString GetSagicorInfoResult;
        
        public GetSagicorInfoResponseBody() {
        }
        
        public GetSagicorInfoResponseBody(BillPaymentGroupAssignment.SagicorLifeServices.ArrayOfString GetSagicorInfoResult) {
            this.GetSagicorInfoResult = GetSagicorInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaySagicorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaySagicor", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequestBody Body;
        
        public PaySagicorRequest() {
        }
        
        public PaySagicorRequest(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class PaySagicorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal amount;
        
        public PaySagicorRequestBody() {
        }
        
        public PaySagicorRequestBody(string accNum, decimal amount) {
            this.accNum = accNum;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaySagicorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaySagicorResponse", Namespace="http://Sagicor.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponseBody Body;
        
        public PaySagicorResponse() {
        }
        
        public PaySagicorResponse(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Sagicor.com/webservices")]
    public partial class PaySagicorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PaySagicorResult;
        
        public PaySagicorResponseBody() {
        }
        
        public PaySagicorResponseBody(bool PaySagicorResult) {
            this.PaySagicorResult = PaySagicorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SagicorLifeConnectSoapChannel : BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SagicorLifeConnectSoapClient : System.ServiceModel.ClientBase<BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap>, BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap {
        
        public SagicorLifeConnectSoapClient() {
        }
        
        public SagicorLifeConnectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SagicorLifeConnectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SagicorLifeConnectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SagicorLifeConnectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.CheckSagicor(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest request) {
            return base.Channel.CheckSagicor(request);
        }
        
        public bool CheckSagicor(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequestBody();
            inValue.Body.userAccNum = userAccNum;
            inValue.Body.userAccEmail = userAccEmail;
            inValue.Body.userAccPhoneNum = userAccPhoneNum;
            BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse retVal = ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).CheckSagicor(inValue);
            return retVal.Body.CheckSagicorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse> BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.CheckSagicorAsync(BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest request) {
            return base.Channel.CheckSagicorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorResponse> CheckSagicorAsync(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.CheckSagicorRequestBody();
            inValue.Body.userAccNum = userAccNum;
            inValue.Body.userAccEmail = userAccEmail;
            inValue.Body.userAccPhoneNum = userAccPhoneNum;
            return ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).CheckSagicorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.GetSagicorInfo(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest request) {
            return base.Channel.GetSagicorInfo(request);
        }
        
        public BillPaymentGroupAssignment.SagicorLifeServices.ArrayOfString GetSagicorInfo(string accNum) {
            BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequestBody();
            inValue.Body.accNum = accNum;
            BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse retVal = ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).GetSagicorInfo(inValue);
            return retVal.Body.GetSagicorInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse> BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.GetSagicorInfoAsync(BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest request) {
            return base.Channel.GetSagicorInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoResponse> GetSagicorInfoAsync(string accNum) {
            BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.GetSagicorInfoRequestBody();
            inValue.Body.accNum = accNum;
            return ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).GetSagicorInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.PaySagicor(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest request) {
            return base.Channel.PaySagicor(request);
        }
        
        public bool PaySagicor(string accNum, decimal amount) {
            BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequestBody();
            inValue.Body.accNum = accNum;
            inValue.Body.amount = amount;
            BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse retVal = ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).PaySagicor(inValue);
            return retVal.Body.PaySagicorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse> BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap.PaySagicorAsync(BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest request) {
            return base.Channel.PaySagicorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorResponse> PaySagicorAsync(string accNum, decimal amount) {
            BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest inValue = new BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequest();
            inValue.Body = new BillPaymentGroupAssignment.SagicorLifeServices.PaySagicorRequestBody();
            inValue.Body.accNum = accNum;
            inValue.Body.amount = amount;
            return ((BillPaymentGroupAssignment.SagicorLifeServices.SagicorLifeConnectSoap)(this)).PaySagicorAsync(inValue);
        }
    }
}
