//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillPaymentGroupAssignment.FlowServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://Flow.com/webservices", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Flow.com/webservices", ConfigurationName="FlowServices.FlowConnectSoap")]
    public interface FlowConnectSoap {
        
        // CODEGEN: Generating message contract since element name userAccNum from namespace http://Flow.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/CheckFlow", ReplyAction="*")]
        BillPaymentGroupAssignment.FlowServices.CheckFlowResponse CheckFlow(BillPaymentGroupAssignment.FlowServices.CheckFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/CheckFlow", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.CheckFlowResponse> CheckFlowAsync(BillPaymentGroupAssignment.FlowServices.CheckFlowRequest request);
        
        // CODEGEN: Generating message contract since element name accNum from namespace http://Flow.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/GetFlowInfo", ReplyAction="*")]
        BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse GetFlowInfo(BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/GetFlowInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse> GetFlowInfoAsync(BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest request);
        
        // CODEGEN: Generating message contract since element name accNum from namespace http://Flow.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/PayFlow", ReplyAction="*")]
        BillPaymentGroupAssignment.FlowServices.PayFlowResponse PayFlow(BillPaymentGroupAssignment.FlowServices.PayFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Flow.com/webservices/PayFlow", ReplyAction="*")]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.PayFlowResponse> PayFlowAsync(BillPaymentGroupAssignment.FlowServices.PayFlowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFlow", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.CheckFlowRequestBody Body;
        
        public CheckFlowRequest() {
        }
        
        public CheckFlowRequest(BillPaymentGroupAssignment.FlowServices.CheckFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class CheckFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userAccNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userAccEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userAccPhoneNum;
        
        public CheckFlowRequestBody() {
        }
        
        public CheckFlowRequestBody(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            this.userAccNum = userAccNum;
            this.userAccEmail = userAccEmail;
            this.userAccPhoneNum = userAccPhoneNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckFlowResponse", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.CheckFlowResponseBody Body;
        
        public CheckFlowResponse() {
        }
        
        public CheckFlowResponse(BillPaymentGroupAssignment.FlowServices.CheckFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class CheckFlowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckFlowResult;
        
        public CheckFlowResponseBody() {
        }
        
        public CheckFlowResponseBody(bool CheckFlowResult) {
            this.CheckFlowResult = CheckFlowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlowInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlowInfo", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequestBody Body;
        
        public GetFlowInfoRequest() {
        }
        
        public GetFlowInfoRequest(BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class GetFlowInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accNum;
        
        public GetFlowInfoRequestBody() {
        }
        
        public GetFlowInfoRequestBody(string accNum) {
            this.accNum = accNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFlowInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlowInfoResponse", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponseBody Body;
        
        public GetFlowInfoResponse() {
        }
        
        public GetFlowInfoResponse(BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class GetFlowInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BillPaymentGroupAssignment.FlowServices.ArrayOfString GetFlowInfoResult;
        
        public GetFlowInfoResponseBody() {
        }
        
        public GetFlowInfoResponseBody(BillPaymentGroupAssignment.FlowServices.ArrayOfString GetFlowInfoResult) {
            this.GetFlowInfoResult = GetFlowInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayFlowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayFlow", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.PayFlowRequestBody Body;
        
        public PayFlowRequest() {
        }
        
        public PayFlowRequest(BillPaymentGroupAssignment.FlowServices.PayFlowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class PayFlowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal amount;
        
        public PayFlowRequestBody() {
        }
        
        public PayFlowRequestBody(string accNum, decimal amount) {
            this.accNum = accNum;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayFlowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayFlowResponse", Namespace="http://Flow.com/webservices", Order=0)]
        public BillPaymentGroupAssignment.FlowServices.PayFlowResponseBody Body;
        
        public PayFlowResponse() {
        }
        
        public PayFlowResponse(BillPaymentGroupAssignment.FlowServices.PayFlowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Flow.com/webservices")]
    public partial class PayFlowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PayFlowResult;
        
        public PayFlowResponseBody() {
        }
        
        public PayFlowResponseBody(bool PayFlowResult) {
            this.PayFlowResult = PayFlowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlowConnectSoapChannel : BillPaymentGroupAssignment.FlowServices.FlowConnectSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlowConnectSoapClient : System.ServiceModel.ClientBase<BillPaymentGroupAssignment.FlowServices.FlowConnectSoap>, BillPaymentGroupAssignment.FlowServices.FlowConnectSoap {
        
        public FlowConnectSoapClient() {
        }
        
        public FlowConnectSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlowConnectSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowConnectSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlowConnectSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.FlowServices.CheckFlowResponse BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.CheckFlow(BillPaymentGroupAssignment.FlowServices.CheckFlowRequest request) {
            return base.Channel.CheckFlow(request);
        }
        
        public bool CheckFlow(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            BillPaymentGroupAssignment.FlowServices.CheckFlowRequest inValue = new BillPaymentGroupAssignment.FlowServices.CheckFlowRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.CheckFlowRequestBody();
            inValue.Body.userAccNum = userAccNum;
            inValue.Body.userAccEmail = userAccEmail;
            inValue.Body.userAccPhoneNum = userAccPhoneNum;
            BillPaymentGroupAssignment.FlowServices.CheckFlowResponse retVal = ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).CheckFlow(inValue);
            return retVal.Body.CheckFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.CheckFlowResponse> BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.CheckFlowAsync(BillPaymentGroupAssignment.FlowServices.CheckFlowRequest request) {
            return base.Channel.CheckFlowAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.CheckFlowResponse> CheckFlowAsync(string userAccNum, string userAccEmail, string userAccPhoneNum) {
            BillPaymentGroupAssignment.FlowServices.CheckFlowRequest inValue = new BillPaymentGroupAssignment.FlowServices.CheckFlowRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.CheckFlowRequestBody();
            inValue.Body.userAccNum = userAccNum;
            inValue.Body.userAccEmail = userAccEmail;
            inValue.Body.userAccPhoneNum = userAccPhoneNum;
            return ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).CheckFlowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.GetFlowInfo(BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest request) {
            return base.Channel.GetFlowInfo(request);
        }
        
        public BillPaymentGroupAssignment.FlowServices.ArrayOfString GetFlowInfo(string accNum) {
            BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest inValue = new BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequestBody();
            inValue.Body.accNum = accNum;
            BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse retVal = ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).GetFlowInfo(inValue);
            return retVal.Body.GetFlowInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse> BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.GetFlowInfoAsync(BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest request) {
            return base.Channel.GetFlowInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.GetFlowInfoResponse> GetFlowInfoAsync(string accNum) {
            BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest inValue = new BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.GetFlowInfoRequestBody();
            inValue.Body.accNum = accNum;
            return ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).GetFlowInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillPaymentGroupAssignment.FlowServices.PayFlowResponse BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.PayFlow(BillPaymentGroupAssignment.FlowServices.PayFlowRequest request) {
            return base.Channel.PayFlow(request);
        }
        
        public bool PayFlow(string accNum, decimal amount) {
            BillPaymentGroupAssignment.FlowServices.PayFlowRequest inValue = new BillPaymentGroupAssignment.FlowServices.PayFlowRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.PayFlowRequestBody();
            inValue.Body.accNum = accNum;
            inValue.Body.amount = amount;
            BillPaymentGroupAssignment.FlowServices.PayFlowResponse retVal = ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).PayFlow(inValue);
            return retVal.Body.PayFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.PayFlowResponse> BillPaymentGroupAssignment.FlowServices.FlowConnectSoap.PayFlowAsync(BillPaymentGroupAssignment.FlowServices.PayFlowRequest request) {
            return base.Channel.PayFlowAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillPaymentGroupAssignment.FlowServices.PayFlowResponse> PayFlowAsync(string accNum, decimal amount) {
            BillPaymentGroupAssignment.FlowServices.PayFlowRequest inValue = new BillPaymentGroupAssignment.FlowServices.PayFlowRequest();
            inValue.Body = new BillPaymentGroupAssignment.FlowServices.PayFlowRequestBody();
            inValue.Body.accNum = accNum;
            inValue.Body.amount = amount;
            return ((BillPaymentGroupAssignment.FlowServices.FlowConnectSoap)(this)).PayFlowAsync(inValue);
        }
    }
}
